name: C CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libcunit1 libcunit1-doc libcunit1-dev libssh2-1-dev
    - name: Build and run tests
      run: |
        gcc -o messaging_module messaging_module.c test_messaging.c -lcunit -lssh2
        ./messaging_module
